services:
  db:
    #使用最新的mariadb穩定版
    image: mariadb:latest
    #將容器取名為mariadb_book
    container_name: mariadb_cart
    #意外停止後，會自動重新啟動
    restart: always
    environment:
      #設定mariadb root的密碼
      MARIADB_ROOT_PASSWORD: 12345678
      #建立資料庫
      MARIADB_DATABASE: cart_db
    #使用的port，AAAA:BBBB，AAAA是外部連接容器使用的port，BBBB是容器內部的port
    ports:
      - "3306:3306"
    #將Mariadb的資料存入這個位置，確保容器重新啟動時，資料庫的資料不會消失
    volumes:
      - db_data:/var/lib/mysql
      
  #redis相關的設定
  redis:
    image: redis:latest
    container_name: redis_cart
    restart: always
    ports:
     - "6379:6379"
     
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq_cart
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  #專案相關的設定
  app:
    #使用同目錄下的Dockerfile，來建立app容器
    build: .
    container_name: java_cart
    restart: always
    ports:
      - "8080:8080"
    #spring專案設定
    environment:
      #改寫application.yaml中的spring: datasource: url:
      #db是資料庫容器的名稱，這邊不能再使用localhost，會無法連接
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/cart_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      #改寫application.yaml中的spring: data: redis: host:
      #redis是容器的名稱
      SPRING_DATA_REDIS_HOST: redis
      #RabbitMQ設定
      SPRING_RABBITMQ_HOST: rabbitmq

volumes:
  db_data:
  rabbitmq_data: